/**
 * BLEObservation — the core immutable record produced by one BLE advertisement packet.
 *
 * Raw observations MUST NEVER be overwritten when deriving features.
 * Fields that the OS does not expose are stored as null, not omitted.
 * Fields whose semantics are uncertain are marked with // UNCERTAIN:
 *
 * Platform notes:
 *   iOS:
 *     - bluetooth_address is NOT exposed by the OS. Always null on iOS.
 *     - platform_peripheral_identifier is a CBPeripheral UUID, recorded exactly as
 *       CoreBluetooth provides it. Its persistence across app reinstall, Bluetooth
 *       off/on, phone reboot, and peripheral reboot is an empirical research question
 *       this harness is designed to answer — do not assume stability or instability.
 *     - solicited_service_uuids and overflow_service_uuids are iOS-specific.
 *     - iOS 13+ no longer exposes MAC addresses to third-party apps at all.
 *
 *   Android:
 *     - bluetooth_address is the MAC address string (may be randomized by the device).
 *     - platform_peripheral_identifier = bluetooth_address on Android.
 *     - advertising_sid, primary_phy, secondary_phy, periodic_advertising_interval
 *       are Android-only (API 26+). react-native-ble-plx does not currently expose
 *       these directly; they require raw scan record parsing (future work).
 */
export interface BLEObservation {
  // ── Identity / platform ──────────────────────────────────────────────────
  observation_id: string;        // UUID v4, generated by this app
  timestamp_utc: string;         // ISO 8601 (e.g. "2026-09-18T14:23:01.234Z")
  timestamp_monotonic: number;   // ms since app process started (performance.now())
  platform: 'ios' | 'android';
  os_version: string;
  app_version: string;
  phone_model: string;

  // ── BLE identity ─────────────────────────────────────────────────────────
  // IMPORTANT: Do NOT assume these fields represent the same underlying identity.
  // Record them separately. They have different stability properties.
  platform_peripheral_identifier: string | null; // iOS: CBPeripheral UUID (rotation behavior is a research question); Android: MAC
  bluetooth_address: string | null;              // null on iOS (not exposed by OS)
  bluetooth_address_type: string | null;         // 'public' | 'random' | null
  device_identifier_available: boolean;

  // ── Human-readable identity ───────────────────────────────────────────────
  local_name: string | null;
  local_name_normalized: string | null; // trimmed + lowercased
  local_name_length: number | null;

  // ── Manufacturer information ──────────────────────────────────────────────
  // Store complete raw bytes. Do NOT hash before storage.
  manufacturer_id: number | null;            // 16-bit Bluetooth SIG company identifier
  manufacturer_data_raw: number[] | null;    // full bytes including the 2-byte company ID
  manufacturer_data_hex: string | null;      // hex string of the above
  manufacturer_data_length: number | null;

  // ── Services ─────────────────────────────────────────────────────────────
  service_uuids: string[] | null;
  service_data_raw: Record<string, number[]> | null; // UUID -> bytes
  solicited_service_uuids: string[] | null;          // iOS only
  overflow_service_uuids: string[] | null;           // iOS only

  // ── Radio / advertisement characteristics ────────────────────────────────
  rssi: number;                                // always present (-127 if unknown)
  tx_power: number | null;
  is_connectable: boolean | null;
  advertising_sid: number | null;              // Android 8+ (API 26+) only
                                               // UNCERTAIN: not directly exposed by react-native-ble-plx;
                                               // future: parse rawScanRecord
  primary_phy: string | null;                  // Android only — UNCERTAIN: same as above
  secondary_phy: string | null;                // Android only — UNCERTAIN: same as above
  periodic_advertising_interval: number | null; // Android only — UNCERTAIN: same as above

  // ── Scan metadata ─────────────────────────────────────────────────────────
  // scanner_timestamp is set to Date.now() at the moment our app's scan callback fires.
  // This is NOT an OS-provided BLE scanner timestamp — react-native-ble-plx does not
  // expose one. It records when our application received and processed the advertisement.
  scanner_timestamp: string;                   // ISO 8601 — our app's receive time, not an OS timestamp
  duplicate_filtering_state: 'on' | 'off' | 'unknown';
  scan_session_id: string;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

export function generateId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = (Math.random() * 16) | 0;
    return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
  });
}

export function base64ToBytes(b64: string): number[] {
  try {
    const binary = atob(b64);
    return Array.from({ length: binary.length }, (_, i) => binary.charCodeAt(i));
  } catch {
    return [];
  }
}

export function bytesToHex(bytes: number[]): string {
  return bytes.map(b => b.toString(16).padStart(2, '0')).join('');
}

/** Extract 16-bit company ID from manufacturer data (first 2 bytes, little-endian). */
export function extractManufacturerId(bytes: number[]): number | null {
  if (bytes.length < 2) return null;
  return (bytes[1] << 8) | bytes[0];
}

export function normalizeName(name: string | null | undefined): string | null {
  if (!name) return null;
  return name.trim().toLowerCase();
}

export function parseServiceData(
  serviceData: Record<string, string> | null | undefined,
): Record<string, number[]> | null {
  if (!serviceData) return null;
  const result: Record<string, number[]> = {};
  for (const [uuid, b64] of Object.entries(serviceData)) {
    result[uuid] = base64ToBytes(b64);
  }
  return result;
}

/** Human-friendly company name for common manufacturer IDs. */
const COMPANY_NAMES: Record<number, string> = {
  0x004c: 'Apple Inc.',
  0x0075: 'Samsung',
  0x00e0: 'Google',
  0x0006: 'Microsoft',
  0x0059: 'Nordic Semiconductor',
  0x000f: 'Broadcom',
  0x001d: 'Qualcomm',
  0x0157: 'Fitbit',
  0x0171: 'Amazon',
  0x0499: 'Ruuvi Innovations',
};

export function companyName(manufacturerId: number | null): string | null {
  if (manufacturerId === null) return null;
  return COMPANY_NAMES[manufacturerId] ?? null;
}
